package com.javier.security_backend.service;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.javier.security_backend.dto.DetectionEventDTO;
import com.javier.security_backend.model.DetectionEvent;
import com.javier.security_backend.repository.DetectionEventRepository;

@Service
public class DetectionEventService {
    
    private static final Logger log = LoggerFactory.getLogger(DetectionEventService.class);
    
    private final DetectionEventRepository repository;
    
    public DetectionEventService(DetectionEventRepository repository) {
        this.repository = repository;
    }
    
    @Transactional
    public DetectionEvent saveEvent(DetectionEventDTO dto) {
        log.info("Saving detection event received from edge module");
        
        try {
            // Create a new DetectionEvent
            // Lombok generates a no-arg constructor and setters for @Data classes
            DetectionEvent event = new DetectionEvent();
            
            // Call setters generated by Lombok @Data
            // These will be available at runtime even if IDE can't see them
            event.setEventId(dto.getEventId());
            event.setEntityType(dto.getEntityType());
            event.setConfidence(dto.getConfidence());
            event.setFrameId(dto.getFrameId());
            event.setTimestamp(Instant.parse(dto.getTimestamp()));
            event.setProcessed(false);
            
            // Save to database
            DetectionEvent saved = repository.save(event);
            log.info("Event saved successfully");
            return saved;
        } catch (IllegalArgumentException | NullPointerException e) {
            log.error("Invalid data in DTO: {}", e.getMessage(), e);
            throw new RuntimeException("Invalid detection event data", e);
        } catch (Exception e) {
            log.error("Error saving event: {}", e.getMessage(), e);
            throw new RuntimeException("Database error saving detection event", e);
        }
    }
    
    public List<DetectionEvent> getAllEvents() {
        return repository.findAll();
    }
    
    public List<DetectionEvent> getUnprocessedEvents() {
        return repository.findByProcessedFalse();
    }
    
    public List<DetectionEvent> getEventsByType(String entityType) {
        return repository.findByEntityType(entityType);
    }
    
    public Optional<DetectionEvent> getEventById(Long id) {
        return repository.findById(id);
    }
    
    @Transactional
    public void markAsProcessed(Long id) {
        repository.findById(id).ifPresent(event -> {
            repository.save(event);
            log.info("Event {} marked as processed", id);
        });
    }
}
